 baseURL = ""
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Hassan Ismail"
theme = "hermit"

copyright = "Hassan Ismail"

[author]
 name = "Hassan Ismail"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

 
 [[params.social]]
    name = "twitter"
    url = "https://twitter.com/"


  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/hassanshakerismail"

  [[params.social]]
    name = "email"
    url = "mailto:h6ismail@uwaterloo.ca"

  [[params.social]]
    name = "github"
    url = "https://github.com/tacituskilgore"

[menu]

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 20

  [[menu.main]]
   name = "Resume"
   url = "resume/"
   weight = 20