baseURL: ""
languageCode: en-us
title: Hassan Ismail
theme: hermit

menu:
  main:
   - identifier: projects
     name: projects
     url: /projects/
     weight: 10
   - identifier: blog
     name: blog
     url: /blog/
     weight: 10
   - identifier: resume
     name: resume
     url: /resume/
     weight: 10



